apiVersion: v1
kind: Namespace
metadata:
  name: dfgdfgdfgdfgfdg-staging
  labels:
    environment-id: env_9b4e6ea0-20cd-41ab-a1bb-78bce70b9cbe
    project-id: project_b98f4ad0-2358-4904-a9d0-b32c98e74a8e
    project-name: dfgdfgdfgdfgfdg
    environment-name: staging
    organization-id: org_628b229c-8bdb-49fd-9fe7-9efd90e925c6
