apiVersion: v1
kind: Namespace
metadata:
  name: sdffsdfsdsdf-staging
  labels:
    environment-id: env_41a33ec0-0ec7-4c52-b818-5aa247886d51
    project-id: project_51089985-5286-4231-a95a-74dadc43f28f
    project-name: sdffsdfsdsdf
    environment-name: staging
    organization-id: org_628b229c-8bdb-49fd-9fe7-9efd90e925c6
