apiVersion: v1
kind: Namespace
metadata:
  name: dfgdfgdfgdfgfdg-prod
  labels:
    environment-id: env_b28456b2-7999-4aa3-a622-cd8bf15f4b42
    project-id: project_b98f4ad0-2358-4904-a9d0-b32c98e74a8e
    project-name: dfgdfgdfgdfgfdg
    environment-name: prod
    organization-id: org_628b229c-8bdb-49fd-9fe7-9efd90e925c6
